
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb  
  ports:
  - name: service
    port: 8086
    protocol: TCP
    targetPort: 8086
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb  
    spec:
      containers:
        - name: influxdb
          image: "influxdb:2.4.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /var/lib/influxdb2          
          ports:
            - name: service
              containerPort: 8086
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        # - name: config
        #   configMap:
        #     name: influxdb
        - name: storage
          emptyDir: {}
            
