
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb  
  ports:
  - name: service
    port: 8086
    protocol: TCP
    targetPort: 8086
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb    
  template:
    metadata:
      labels:
        app: influxdb  
    spec:
      containers:
        - name: influxdb
          image: "influxdb:2.4.0"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: influxdb-envs           
          volumeMounts:
            - name: storage
              mountPath: /var/lib/influxdb2          
          ports:
            - name: service
              containerPort: 8086
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"            
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi          
            
