apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: non-otel-instrumentation
spec:
  resource:
    addK8sUIDAttributes: true
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on